/*
 * This file is generated by jOOQ.
*/
package com.example.stherokubackend.database.tables.records;


import com.example.stherokubackend.database.tables.Profile;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileRecord extends UpdatableRecordImpl<ProfileRecord> implements Record5<String, String, Integer, String, String> {

    private static final long serialVersionUID = -1467710435;

    /**
     * Setter for <code>stherokubackend_dev.profile.businessName</code>.
     */
    public void setBusinessname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>stherokubackend_dev.profile.businessName</code>.
     */
    public String getBusinessname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>stherokubackend_dev.profile.businessLocation</code>.
     */
    public void setBusinesslocation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stherokubackend_dev.profile.businessLocation</code>.
     */
    public String getBusinesslocation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stherokubackend_dev.profile.id</code>.
     */
    public void setId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>stherokubackend_dev.profile.id</code>.
     */
    public Integer getId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>stherokubackend_dev.profile.businessCategory</code>.
     */
    public void setBusinesscategory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stherokubackend_dev.profile.businessCategory</code>.
     */
    public String getBusinesscategory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stherokubackend_dev.profile.businessImage</code>.
     */
    public void setBusinessimage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>stherokubackend_dev.profile.businessImage</code>.
     */
    public String getBusinessimage() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Integer, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Integer, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Profile.PROFILE.BUSINESSNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Profile.PROFILE.BUSINESSLOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Profile.PROFILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Profile.PROFILE.BUSINESSCATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Profile.PROFILE.BUSINESSIMAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getBusinessname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBusinesslocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getBusinesscategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getBusinessimage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getBusinessname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBusinesslocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getBusinesscategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBusinessimage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord value1(String value) {
        setBusinessname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord value2(String value) {
        setBusinesslocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord value3(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord value4(String value) {
        setBusinesscategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord value5(String value) {
        setBusinessimage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord values(String value1, String value2, Integer value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfileRecord
     */
    public ProfileRecord() {
        super(Profile.PROFILE);
    }

    /**
     * Create a detached, initialised ProfileRecord
     */
    public ProfileRecord(String businessname, String businesslocation, Integer id, String businesscategory, String businessimage) {
        super(Profile.PROFILE);

        set(0, businessname);
        set(1, businesslocation);
        set(2, id);
        set(3, businesscategory);
        set(4, businessimage);
    }
}
