/*
 * This file is generated by jOOQ.
*/
package com.example.stherokubackend.database;


import com.example.stherokubackend.database.tables.Profile;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in stherokubackend_dev
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>stherokubackend_dev.profile</code>.
     */
    public static final Profile PROFILE = com.example.stherokubackend.database.tables.Profile.PROFILE;
}
